# -*- coding: utf-8 -*-
"""Número ganador

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-BqPn0WKrr_FwxK4L_1LuTeCruk6QnDw
"""

import pandas as pd

df = pd.read_csv('lty-lottery-tickets.csv')

ganador = int(input('Digita un número de lotería '))

print(df[df["Ticket Number"]==ganador])